version: "3.7"
services:
  app:
    container_name: project-training1
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
